### ISSUE TITLE
Impossible to enable or set oe_theme as default using UI

### ISSUE THREAD

**Issue by LOBsTerr** [openeuropa/oe_theme#51]
###Problem

Theme can't be enable through UI. I see an error "The oe_theme theme was not found."
Through drush or drupal console the theme is also can't be enabled.

### How to reproduce
1) Install new D8 site
2) Add oe_theme to the composer.json
3) Go to UI and try to enable 
4) You will see the message that theme is not found

### Expected behaviour
I should be able to enable and set as default oe theme

**Comment by LOBsTerr** [comment]
I have debugged it a little bit. It looks like the problem is related to dependencies.
The only dependency we have is oe_theme_helper, when I enable it.
I can't access theme UI anymore. I see an exception

```
InvalidArgumentException: The theme oe_theme does not exist. in Drupal\Core\Extension\ThemeHandler->getTheme() (line 489 of /home/nikolay/www/iot/web/core/lib/Drupal/Core/Extension/ThemeHandler.php).
```

**Comment by LOBsTerr** [comment]
So, if we remove 'oe_theme_helper' dependency, the theme can be enabled and then we can enable oe_theme_helper separately, but then I face another issue:
```
2018/03/19 10:51:56 [error] 31830#31830: *245 FastCGI sent in stderr: "PHP message: Uncaught PHP Exception Twig_Error_Loader: "The "themes/contrib/oe_theme/templates/components" directory does not exist ("/var/www/html/drupal_console_site/web/themes/contrib/oe_theme/templates/components")." at /var/www/html/drupal_console_site/vendor/twig/twig/lib/Twig/Loader/Filesystem.php line 101" while reading response header from upstream, client: 127.0.0.1, server: dc, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "dc"
```

The same error, when I install website using oe_theme build

**Comment by LOBsTerr** [comment]
ok, The error from the previous comment happened, because I didn't run npm install

**Comment by brummbar** [comment]
@LOBsTerr , I took a look at this issue and found the cause. The current implementation of the `oe_theme` relies on two patches applied for `drupal/core`. You can find these two patches in the `composer.json` in the root folder of this theme.
The patches are applied properly when using the build system inside the theme, or any other system that lists `drupal/core` as dependency.

If you install drupal with `composer create-project drupal/drupal drupal8` or with the package download, automatic patching of core won't be possible. You have to specify the patches in the composer.json or patch them manually if you use package download (which you shouldn't use anyway).

If you are using an installation where `drupal/core` is listed as dependency (for example using [pfrenssen/drupal-project](https://github.com/pfrenssen/drupal-project)), after adding the oe_theme as dependency you have to delete the drupal/core package and run a `composer install` so that it will be patched with the patches discovered in the oe_theme.

**Comment by LOBsTerr** [comment]
@brummbar Thank you for the answer. I will adapt our build script accordingly. I just have found it also :)

https://www.drupal.org/project/drupal/issues/474684

**Comment by Fefaine** [comment]
woow solved today 🎉 
https://www.drupal.org/project/drupal/issues/474684
